import type { TickTest } from "./tickTests";

/**
 * The second shelf of forty-second tests: the questions people actually
 * type into TikTok search, some serious, some for fun. The fun ones are
 * labelled as such and their results stay playful; they still count,
 * never diagnose, and each one leads into the full test that can say more.
 */
export const MORE_TICK_TESTS: TickTest[] = [
  {
    slug: "is-my-boyfriend-toxic",
    question: "Is my boyfriend toxic?",
    short: "Is my boyfriend toxic?",
    emoji: "☠️",
    intro: "Tap everything he has actually done. Not once in a bad mood, but more than once.",
    verb: "ticked",
    bg: "#F7D9D9",
    fg: "#6E1B1B",
    items: [
      { id: "t1", text: "Makes you feel stupid in front of people", group: "disrespect" },
      { id: "t2", text: "Jokes about your body or your looks", group: "disrespect" },
      { id: "t3", text: "Rolls his eyes when you talk about your feelings", group: "disrespect" },
      { id: "t4", text: "Never says sorry, or says \"sorry you feel that way\"", group: "blame" },
      { id: "t5", text: "Turns every argument into what you did wrong", group: "blame" },
      { id: "t6", text: "Brings up your past mistakes in every fight", group: "blame" },
      { id: "t7", text: "Gives you the silent treatment for days", group: "punish" },
      { id: "t8", text: "Goes cold when you have a night out without him", group: "control", flag: true },
      { id: "t9", text: "Wants to know where you are all the time", group: "control", flag: true },
      { id: "t10", text: "Has opinions on what you wear", group: "control", flag: true },
      { id: "t11", text: "Talks badly about your friends until you see them less", group: "control", flag: true },
      { id: "t12", text: "Amazing one week, awful the next", group: "punish" },
      { id: "t13", text: "You walk on eggshells around his moods", group: "punish" },
      { id: "t14", text: "Flirts with others and calls you jealous", group: "blame" },
      { id: "t15", text: "Your friends have stopped liking him", group: "outside" },
      { id: "t16", text: "You've stopped telling people what he does", group: "outside" },
    ],
    groups: {
      disrespect: { label: "Disrespect", does: "Small put-downs that add up. Contempt is the single strongest predictor of relationships going wrong in John Gottman's research." },
      blame: { label: "Always your fault", does: "Every problem ends up being yours. It means nothing he does ever gets discussed." },
      punish: { label: "Moods as punishment", does: "Silence and swings that keep you careful. Walking on eggshells is the feeling of being managed." },
      control: { label: "Control", does: "Your time, your clothes, your friends. Each is small; together they shrink your life around him." },
      outside: { label: "What others see", does: "When you start hiding things from people who love you, part of you already knows how it looks." },
    },
    verdicts: {
      none: "You didn't tick anything. Whatever's bothering you, it isn't these.",
      few: "A couple of these is a partner with bad habits, which is most partners. Worth saying something, not worth panicking over.",
      pattern: "That's a pattern, not a bad week. You're not being dramatic for noticing, and you're allowed to want better than this.",
      system: "That's most of the list. This isn't a rough patch, it's how the relationship works, and it's worth talking to someone outside it about.",
    },
    support: { min: 2, text: "Some of what you ticked is about control: your time, your friends, what you wear. If that's happening, please talk to someone outside the relationship. In the UK, Refuge runs a free 24-hour line on 0808 2000 247." },
    full: { href: "/is-he-manipulative", label: "Take the full manipulation test, free" },
    report: {
      pitch: "See exactly which tactics he uses, and what to say back.",
      bullets: [
        "Each manipulation tactic scored separately",
        "Your own answers quoted back to you",
        "The exact sentence to use the next time each one happens",
        "A step-by-step plan that doesn't need his cooperation",
      ],
    },
    seo: { title: "Is My Boyfriend Toxic? 16 Signs, Tap The Ones He Does", description: "Sixteen things toxic boyfriends do. Tap the ones yours does and get an honest answer in 40 seconds. Free, no sign-up." },
  },
  {
    slug: "is-my-boyfriend-stupid",
    fun: true,
    question: "Is my boyfriend stupid, or just clueless?",
    short: "Is my boyfriend stupid?",
    emoji: "🤡",
    intro: "Just for fun. Tap everything he has genuinely done.",
    verb: "ticked",
    bg: "#FFF1C9",
    fg: "#6A4B00",
    items: [
      { id: "b1", text: "Asks where the ketchup is while looking at it", group: "house" },
      { id: "b2", text: "\"You didn't tell me\" (you told him three times)", group: "house" },
      { id: "b3", text: "Thinks the laundry does itself", group: "house" },
      { id: "b4", text: "Missed a hint so big it had a neon sign", group: "hints" },
      { id: "b5", text: "\"What's wrong?\" \"Nothing.\" He believed you", group: "hints" },
      { id: "b6", text: "Got you something for his own hobby as a gift", group: "hints" },
      { id: "b7", text: "Tries to fix it when you just wanted a hug", group: "feelings" },
      { id: "b8", text: "Asks \"are you on your period?\" mid-argument", group: "feelings" },
      { id: "b9", text: "Replies \"ok\" to a paragraph", group: "feelings" },
      { id: "b10", text: "Remembers every football score, forgets your mum's name", group: "memory" },
      { id: "b11", text: "Forgot an anniversary, then argued about the date", group: "memory" },
      { id: "b12", text: "But he'd still drive across town at 2am for you", group: "sweet" },
    ],
    groups: {
      house: { label: "Household blindness", does: "Things are invisible to him until you point at them. Annoying, very common, and fixable with blunt instructions." },
      hints: { label: "Hint-proof", does: "Hints do not reach him. Research on couples is fairly consistent here: clear requests work far better than hoping to be guessed." },
      feelings: { label: "Emotionally clueless", does: "He hears a problem and reaches for a solution, or for the wrong question. Clueless is fixable. Not caring is a different thing." },
      memory: { label: "Selective memory", does: "He remembers what interests him. Worth a direct word if it's the things that matter to you." },
      sweet: { label: "Redeeming feature", does: "Clueless and kind is a very workable combination." },
    },
    verdicts: {
      none: "Suspiciously competent. Keep him.",
      few: "He's a normal man. Mildly baffling, fundamentally fine.",
      pattern: "Certified clueless. Not stupid, just running on very low bandwidth for anything he isn't told directly.",
      system: "He is, lovingly, a golden retriever. The real question is whether he's clueless or just not paying attention to you, and those are very different things.",
    },
    full: { href: "/partners-attachment-style", label: "Clueless or distant? Find his attachment style" },
    report: {
      pitch: "Find out whether it's cluelessness or emotional distance.",
      bullets: [
        "Where he sits on the two attachment axes, scored",
        "What is most likely behind the moments he tunes out",
        "What you can actually change, and what you can't",
        "A step-by-step plan for your side of it",
      ],
    },
    seo: { title: "Is My Boyfriend Stupid? A 30-Second Test (Just For Fun)", description: "Twelve things clueless boyfriends do. Tap the ones yours does and find out if he's stupid or just clueless. Free, just for fun." },
  },
  {
    slug: "is-my-friend-a-pick-me",
    fun: true,
    question: "Is my friend a pick-me girl?",
    short: "Is she a pick-me?",
    emoji: "🙋‍♀️",
    intro: "Mostly for fun. Tap everything she has actually said or done.",
    verb: "ticked",
    bg: "#FDE2F0",
    fg: "#6E1A4A",
    items: [
      { id: "k1", text: "\"I'm not like other girls\"", group: "notlike" },
      { id: "k2", text: "\"I just get on better with guys\"", group: "notlike" },
      { id: "k3", text: "\"Girls are so much drama\"", group: "notlike" },
      { id: "k4", text: "Makes a point of eating burgers and hating makeup", group: "notlike" },
      { id: "k5", text: "Laughs loudest at sexist jokes", group: "boys" },
      { id: "k6", text: "Changes her whole personality when boys arrive", group: "boys" },
      { id: "k7", text: "Tells your boyfriend he's \"so funny\", a lot", group: "boys" },
      { id: "k8", text: "\"I'm so low maintenance, I don't need anything\"", group: "boys" },
      { id: "k9", text: "Agrees with the guys against you in a debate", group: "rival" },
      { id: "k10", text: "Has an opinion on how much effort you make", group: "rival" },
      { id: "k11", text: "Tells you what \"guys actually think\" about you", group: "rival" },
      { id: "k12", text: "Is lovely one to one, different in a group", group: "rival" },
    ],
    groups: {
      notlike: { label: "Not like other girls", does: "Standing out by putting other women down. Usually insecurity wearing a personality." },
      boys: { label: "Performing for the boys", does: "Her attention shifts to whoever's approval she wants. Tiring to watch, more tiring to be friends with." },
      rival: { label: "Quietly competing", does: "You're treated as competition rather than a teammate. This is the part that actually affects your friendship." },
    },
    verdicts: {
      none: "Not a pick-me. She's just your friend.",
      few: "A little pick-me energy. Most people have a phase. Probably harmless.",
      pattern: "Pick-me confirmed. The funny part is the performance; the part worth watching is whether she competes with you.",
      system: "Full pick-me. It's usually insecurity, but if she's competing with you rather than cheering for you, the friendship is costing you more than it looks.",
    },
    full: { href: "/toxic-friend-test", label: "Is it harmless, or toxic? Full friend test" },
    report: {
      pitch: "Find out if she's just annoying or actually bad for you.",
      bullets: [
        "The friendship scored across seven dimensions, including its impact on you",
        "What your two highest scores mean together",
        "When a quiet fade works better than a confrontation",
        "Word-for-word scripts and a step-by-step plan",
      ],
    },
    seo: { title: "Is My Friend A Pick-Me Girl? 30-Second Test", description: "Twelve pick-me girl signs. Tap the ones your friend does and find out if she's a pick-me. Free, no sign-up, just for fun." },
  },
  {
    slug: "is-he-a-mamas-boy",
    fun: true,
    question: "Is he a mama's boy?",
    short: "Is he a mama's boy?",
    emoji: "👩‍👦",
    intro: "Half joking. Tap everything that's actually true.",
    verb: "ticked",
    bg: "#E6F0DA",
    fg: "#34511A",
    items: [
      { id: "o1", text: "Calls his mum every single day", group: "contact" },
      { id: "o2", text: "Tells her about your arguments", group: "sides" },
      { id: "o3", text: "\"My mum doesn't do it like that\"", group: "compare" },
      { id: "o4", text: "She still does his washing", group: "care" },
      { id: "o5", text: "She has a key to your place", group: "sides" },
      { id: "o6", text: "Plans change the second she calls", group: "sides" },
      { id: "o7", text: "He's never once taken your side against her", group: "sides" },
      { id: "o8", text: "She texts him more than you do", group: "contact" },
      { id: "o9", text: "He can't cook anything she didn't teach him", group: "care" },
      { id: "o10", text: "Compares your food to hers, out loud", group: "compare" },
      { id: "o11", text: "Every holiday is automatically at hers", group: "sides" },
      { id: "o12", text: "Honestly, he's very sweet to her", group: "sweet" },
    ],
    groups: {
      contact: { label: "Always in touch", does: "Close to his mum is a good sign in lots of ways. It's only a problem if there's no room left." },
      sides: { label: "Whose side he's on", does: "The real test. Couples therapists see this constantly: a partner who can't put the relationship first will keep putting you second." },
      compare: { label: "The comparison", does: "You are not auditioning for a role she already has." },
      care: { label: "Still looked after", does: "He's never had to learn. Not a crime, but it lands on you." },
      sweet: { label: "The good part", does: "Men who treat their mothers well often treat partners well too. The key word is \"also\"." },
    },
    verdicts: {
      none: "Not a mama's boy. Possibly suspiciously independent.",
      few: "He loves his mum. That's a green flag, mostly.",
      pattern: "Mama's boy, yes. The only part that matters is whether he can choose you when it counts.",
      system: "His mum is basically in the relationship. That's not fixable with jokes; it needs one clear conversation about where you come in.",
    },
    full: { href: "/partners-attachment-style", label: "Take the full test on how he attaches" },
    report: {
      pitch: "See how he bonds, and why it's so hard for him to put you first.",
      bullets: [
        "Where he sits on the two attachment axes, scored",
        "What is most likely behind his pattern",
        "What you can actually change, and what you can't",
        "A step-by-step plan for your side of it",
      ],
    },
    seo: { title: "Is He A Mama's Boy? 30-Second Test", description: "Twelve signs he's a mama's boy. Tap the ones that fit and find out. Free, no sign-up, half joking." },
  },
  {
    slug: "is-he-just-not-that-into-you",
    question: "Is he just not that into you?",
    short: "Is he into you?",
    emoji: "🫠",
    intro: "Tap everything that's true about how he's been lately.",
    verb: "ticked",
    bg: "#E3E6F8",
    fg: "#27306B",
    items: [
      { id: "n1", text: "You always text first", group: "effort" },
      { id: "n2", text: "Replies take hours, but he's online", group: "effort" },
      { id: "n3", text: "He never makes plans, only agrees to yours", group: "effort" },
      { id: "n4", text: "Plans are always last minute", group: "effort" },
      { id: "n5", text: "He only gets in touch late at night", group: "convenience" },
      { id: "n6", text: "You've never met his friends", group: "hidden" },
      { id: "n7", text: "You're not on his socials", group: "hidden" },
      { id: "n8", text: "\"I'm not looking for anything serious right now\"", group: "said" },
      { id: "n9", text: "\"I'm just really busy\" for weeks", group: "said" },
      { id: "n10", text: "He never asks about your day", group: "interest" },
      { id: "n11", text: "He forgets things you told him that mattered", group: "interest" },
      { id: "n12", text: "He's warmer when you pull back", group: "convenience" },
      { id: "n13", text: "You explain his behaviour to your friends a lot", group: "you" },
      { id: "n14", text: "You feel anxious more than happy", group: "you" },
    ],
    groups: {
      effort: { label: "Effort", does: "Interest shows up as effort. When all of it comes from you, the imbalance is the answer." },
      convenience: { label: "On his terms", does: "You're wanted when it suits him. Warmer when you pull back is the hot-and-cold that keeps people hooked." },
      hidden: { label: "Kept separate", does: "Not being part of his world after a while is its own message." },
      said: { label: "What he told you", does: "When someone says they don't want anything serious, the kindest thing is to believe them." },
      interest: { label: "Curiosity", does: "People ask about what they care about. Not being asked is information." },
      you: { label: "How it feels", does: "Anxious more than happy is the most honest measure there is." },
    },
    verdicts: {
      none: "Sounds like he's into you. Enjoy it.",
      few: "A couple of these could just be a busy guy. Watch whether the effort goes up or down.",
      pattern: "The effort isn't matching yours. That's not you being too much; it's him giving you less.",
      system: "Honestly? He's told you with everything except words, and sometimes with words too. You deserve someone who's obviously glad you exist.",
    },
    full: { href: "/partners-attachment-style", label: "Avoidant or uninterested? Find out, free" },
    report: {
      pitch: "Find out whether he's avoidant or just not invested.",
      bullets: [
        "Where he sits on the two attachment axes, scored",
        "What is most likely behind his distance",
        "What you can actually change, and what you can't",
        "A step-by-step plan for your side of it",
      ],
    },
    seo: { title: "Is He Just Not That Into You? 14 Signs, 40 Seconds", description: "Fourteen signs he isn't that into you. Tap the ones that fit and get an honest answer. Free, no sign-up." },
  },
  {
    slug: "am-i-the-toxic-one",
    question: "Wait... am I the toxic one?",
    short: "Am I the toxic one?",
    emoji: "🪞",
    intro: "Brave one. Tap everything you've honestly done in a relationship. Nobody sees this.",
    verb: "ticked",
    bg: "#EDE4DA",
    fg: "#4A3521",
    items: [
      { id: "i1", text: "Gone through their phone", group: "check" },
      { id: "i2", text: "Checked who they're following or liking", group: "check" },
      { id: "i3", text: "Brought up an old fight to win a new one", group: "fight" },
      { id: "i4", text: "Said something to hurt on purpose", group: "fight" },
      { id: "i5", text: "Given the silent treatment", group: "punish" },
      { id: "i6", text: "Gone cold so they'd chase me", group: "test" },
      { id: "i7", text: "Picked a fight when I really wanted reassurance", group: "test" },
      { id: "i8", text: "Threatened to leave without meaning it", group: "test" },
      { id: "i9", text: "Got jealous of their friends", group: "check" },
      { id: "i10", text: "Made them feel guilty for a night out", group: "punish" },
      { id: "i11", text: "Blamed them for how I felt", group: "fight" },
      { id: "i12", text: "Apologised properly afterwards", group: "repair" },
      { id: "i13", text: "Tried to understand why I did it", group: "repair" },
      { id: "i14", text: "Taken this test because I'm worried I am", group: "repair" },
    ],
    groups: {
      check: { label: "Checking", does: "Usually fear, not control. Still, it chips at trust from both sides." },
      fight: { label: "Fighting to win", does: "When winning the argument matters more than what it was about, both people lose." },
      punish: { label: "Punishing", does: "Silence and guilt used to make a point. Understandable when you're hurt; damaging when it's how you cope." },
      test: { label: "Testing", does: "A question in disguise: do you really care? They answer the disguise, not the question." },
      repair: { label: "Repair", does: "The difference between someone who behaves badly sometimes and someone toxic is mostly this: repair, and wanting to change." },
    },
    verdicts: {
      none: "You're not the toxic one. Or you skipped the questions. We'll assume the first.",
      few: "Everyone has a few of these. Being human in a relationship isn't the same as being toxic.",
      pattern: "Some of how you cope with fear hurts the relationship. That's not a character verdict; it's usually an alarm set too sensitive, and it's very changeable. Most toxic people don't take this test.",
      system: "There's a real pattern here, and you already feel it, or you wouldn't be here. That self-awareness is the hardest part. The rest is learnable.",
    },
    full: { href: "/why-do-i-sabotage-relationships", label: "Find out why you do it, free" },
    report: {
      pitch: "See the pattern underneath, and what to do instead.",
      bullets: [
        "Fear of closeness, the rejection alarm, testing, worthiness and withdrawal, each scored",
        "Where your pattern most likely came from",
        "The one change that would help most, right now",
      ],
    },
    seo: { title: "Am I The Toxic One In My Relationship? Honest 40-Second Test", description: "Fourteen things people do in relationships. Tap the ones you've done and get an honest, kind answer. Free, private, no sign-up." },
  },
  {
    slug: "does-he-have-narcissistic-traits",
    question: "Does he have narcissistic traits?",
    short: "Is he a narcissist?",
    emoji: "👑",
    intro: "Nobody can diagnose anyone from a list. But you can count what you've seen. Tap everything that's true.",
    verb: "ticked",
    bg: "#F3E3C4",
    fg: "#5C3F0A",
    items: [
      { id: "z1", text: "Needs constant praise, and sulks without it", group: "admiration" },
      { id: "z2", text: "Every story ends up being about him", group: "admiration" },
      { id: "z3", text: "Can't take the smallest criticism", group: "fragile" },
      { id: "z4", text: "Rages or goes cold when he's embarrassed", group: "fragile" },
      { id: "z5", text: "Never genuinely apologises", group: "fragile" },
      { id: "z6", text: "Charming to everyone else, different at home", group: "mask" },
      { id: "z7", text: "Rewrites what happened so he's the good guy", group: "mask" },
      { id: "z8", text: "Seems annoyed when you succeed", group: "empathy" },
      { id: "z9", text: "Bored or irritated when you're upset", group: "empathy" },
      { id: "z10", text: "Uses people, then drops them", group: "empathy" },
      { id: "z11", text: "Swept you off your feet, then turned critical", group: "cycle" },
      { id: "z12", text: "Keeps exes around to make you feel insecure", group: "cycle" },
      { id: "z13", text: "Believes the rules don't apply to him", group: "admiration" },
      { id: "z14", text: "Makes you feel lucky he's with you", group: "cycle" },
    ],
    groups: {
      admiration: { label: "Needs admiration", does: "A constant need to be seen as special. It's the most visible trait and, on its own, the least serious." },
      fragile: { label: "Fragile ego", does: "Huge reactions to small criticism. Under the confidence is something that can't bear being wrong." },
      mask: { label: "Two faces", does: "Public charm, private coldness, and a version of events where he's always right. It's why people outside don't believe you." },
      empathy: { label: "Low empathy", does: "Your feelings are an inconvenience. This is the trait that does the most damage in a relationship." },
      cycle: { label: "Idealise, then devalue", does: "Swept up, then cut down. The early high is what keeps people waiting for it to come back." },
    },
    verdicts: {
      none: "None of these. Whatever he is, it isn't this.",
      few: "A few of these is someone with a big ego, which is a lot of people. Not a label.",
      pattern: "That's a real cluster of narcissistic traits. Only a clinician can diagnose, and you don't need a diagnosis to decide how you want to be treated.",
      system: "That's nearly all of it. Whatever the label, living with this is exhausting and it tends not to change on its own. Please don't carry it alone.",
    },
    support: { min: 3, text: "If living with him has left you walking on eggshells or afraid, please talk to someone outside the relationship. In the UK, Refuge runs a free 24-hour line on 0808 2000 247." },
    full: { href: "/is-he-manipulative", label: "Take the full manipulation test, free" },
    report: {
      pitch: "See which of his tactics are doing the damage, and how to respond.",
      bullets: [
        "Each manipulation tactic scored separately",
        "Your own answers quoted back to you",
        "The exact sentence to use the next time each one happens",
        "A step-by-step plan that doesn't need his cooperation",
      ],
    },
    seo: { title: "Is He A Narcissist? 14 Traits, Tap The Ones You've Seen", description: "Fourteen narcissistic traits. Tap the ones you've seen in him and get an honest read in 40 seconds. Free, no sign-up, no diagnosis." },
  },
  {
    slug: "is-it-a-situationship",
    question: "Is it a relationship, or a situationship?",
    short: "Is it a situationship?",
    emoji: "🌫️",
    intro: "Tap everything that's true about the two of you right now.",
    verb: "ticked",
    bg: "#E2EEF3",
    fg: "#1F4552",
    items: [
      { id: "u1", text: "It's been months and there's no label", group: "label" },
      { id: "u2", text: "\"Let's not put a label on it\"", group: "label" },
      { id: "u3", text: "You don't know if you can see other people", group: "label" },
      { id: "u4", text: "Plans are mostly late at night", group: "shape" },
      { id: "u5", text: "You've never been on a proper date", group: "shape" },
      { id: "u6", text: "You haven't met his friends", group: "world" },
      { id: "u7", text: "You don't know what he's doing this weekend", group: "world" },
      { id: "u8", text: "You're scared to ask \"what are we?\"", group: "you" },
      { id: "u9", text: "You act like you're fine with it", group: "you" },
      { id: "u10", text: "You'd be hurt if he dated someone else", group: "you" },
      { id: "u11", text: "He's affectionate in private, distant in public", group: "shape" },
      { id: "u12", text: "The future never comes up", group: "label" },
    ],
    groups: {
      label: { label: "No label", does: "Undefined suits whoever wants less. Usually that's not the one taking this test." },
      shape: { label: "Its shape", does: "Late nights and no dates is a relationship-shaped arrangement without the relationship." },
      world: { label: "Outside his world", does: "You're in his evenings, not his life." },
      you: { label: "What you want", does: "The giveaway: you'd be hurt, and you're pretending you wouldn't. That's the part that matters." },
    },
    verdicts: {
      none: "That's a relationship. Label or not, it sounds like one.",
      few: "Early days can look like this. The question is whether it's heading somewhere.",
      pattern: "Situationship, yes. It's fine if it's what you both want. The problem is when one of you is pretending.",
      system: "It's a situationship, and you want more than it's giving you. You're allowed to ask \"what are we?\", and his answer is information, whatever it is.",
    },
    full: { href: "/why-do-i-pick-bad-guys", label: "Why do you end up here? Find out, free" },
    report: {
      pitch: "Find out why this kind of connection keeps finding you.",
      bullets: [
        "Your partner-selection pattern, scored dimension by dimension",
        "Why the wrong men find it so easy to read, for your scores",
        "Your own answers quoted back to you",
        "Word-for-word scripts and a step-by-step plan",
      ],
    },
    seo: { title: "Am I In A Situationship? 30-Second Test", description: "Twelve signs you're in a situationship, not a relationship. Tap the ones that fit and get an honest answer. Free, no sign-up." },
  },
  {
    slug: "are-you-the-therapist-friend",
    fun: true,
    question: "Are you the therapist friend?",
    short: "The therapist friend?",
    emoji: "🛋️",
    intro: "Mostly for fun. Tap everything that sounds like you.",
    verb: "ticked",
    bg: "#E4F2E0",
    fg: "#2C4F22",
    items: [
      { id: "h1", text: "Friends send you screenshots to decode", group: "role" },
      { id: "h2", text: "You've given advice at 2am more than once", group: "role" },
      { id: "h3", text: "People say \"you're so easy to talk to\"", group: "role" },
      { id: "h4", text: "You know everyone's drama, nobody knows yours", group: "oneway" },
      { id: "h5", text: "When you're sad, you deal with it alone", group: "oneway" },
      { id: "h6", text: "Friends go quiet when you finally need them", group: "oneway" },
      { id: "h7", text: "You feel guilty not replying straight away", group: "cost" },
      { id: "h8", text: "You're tired after seeing certain friends", group: "cost" },
      { id: "h9", text: "You say \"I'm fine\" and change the subject", group: "oneway" },
      { id: "h10", text: "You've been called \"the mum of the group\"", group: "role" },
      { id: "h11", text: "You secretly wish someone would ask how you are", group: "cost" },
      { id: "h12", text: "You'd honestly make a great therapist", group: "role" },
    ],
    groups: {
      role: { label: "The role", does: "You're good at this. That's a real gift, and it's also why people keep bringing you their problems." },
      oneway: { label: "One-way traffic", does: "Support flows out, not in. Not because nobody cares, but because you've taught everyone you don't need it." },
      cost: { label: "The cost", does: "Tired, guilty, quietly wishing someone would ask. The therapist friend needs a therapist friend." },
    },
    verdicts: {
      none: "You're not the therapist friend. You might be the fun friend. Also important.",
      few: "A good listener, but it isn't running your life. Nice balance.",
      pattern: "Therapist friend, confirmed. You give a lot. The question is whether anyone gives back.",
      system: "You're everyone's therapist and nobody's patient. You deserve friends who ask about you too, and you're allowed to go first.",
    },
    full: { href: "/friend-group-role", label: "Find your full friend group role, free" },
    report: {
      pitch: "See the role you play in your group, and what it costs you.",
      bullets: [
        "Your role in the group, with every trait scored",
        "The resentment trap your role tends to fall into",
        "How the others in your group are likely to see you",
        "A plan for right now, this week and this month",
      ],
    },
    seo: { title: "Are You The Therapist Friend? 30-Second Test", description: "Twelve signs you're the therapist friend. Tap the ones that fit. Free, no sign-up, mostly for fun." },
  },
];
