export const gaslightingQuestions = [
  { id: 1, text: "He tells me something did not happen even when I clearly remember it.", subscale: "reality_denial", isCritical: true },
  { id: 2, text: "He insists I said or meant something I know I did not.", subscale: "reality_denial", isCritical: false },
  { id: 3, text: "He tells me my memory is unreliable during disagreements.", subscale: "reality_denial", isCritical: false },
  { id: 4, text: "He acts certain about a false version of events until I start doubting myself.", subscale: "reality_denial", isCritical: true },
  { id: 5, text: "He rewrites shared conversations in ways that favor him.", subscale: "reality_denial", isCritical: false },
  { id: 6, text: "He denies promises, plans, or statements he clearly made.", subscale: "reality_denial", isCritical: false },
  { id: 7, text: "He says I am imagining things when I point out a pattern.", subscale: "reality_denial", isCritical: true },
  { id: 8, text: "After arguments, I feel less sure of what actually happened.", subscale: "reality_denial", isCritical: false },
  { id: 9, text: "He tells me I am too sensitive when I bring up something hurtful.", subscale: "invalidation", isCritical: false },
  { id: 10, text: "He treats my feelings as dramatic, irrational, or excessive.", subscale: "invalidation", isCritical: false },
  { id: 11, text: "He says I am making a big deal out of nothing.", subscale: "invalidation", isCritical: false },
  { id: 12, text: "He hides behind “I was just joking” after saying something hurtful.", subscale: "invalidation", isCritical: false },
  { id: 13, text: "He makes me feel embarrassed for having emotional needs.", subscale: "invalidation", isCritical: false },
  { id: 14, text: "He acts like my concerns are childish or unreasonable.", subscale: "invalidation", isCritical: false },
  { id: 15, text: "He responds to pain with eye-rolling, smirks, or mockery.", subscale: "invalidation", isCritical: false },
  { id: 16, text: "I leave serious conversations feeling foolish for bringing them up.", subscale: "invalidation", isCritical: false },
  { id: 17, text: "He turns discussions about his behavior into conversations about my flaws.", subscale: "blame_reversal", isCritical: false },
  { id: 18, text: "He blames me for his lying, distance, coldness, or outbursts.", subscale: "blame_reversal", isCritical: true },
  { id: 19, text: "He says I caused the exact problem I was trying to address.", subscale: "blame_reversal", isCritical: false },
  { id: 20, text: "He makes me apologize after he crosses a line.", subscale: "blame_reversal", isCritical: true },
  { id: 21, text: "He brings up unrelated mistakes to avoid the original issue.", subscale: "blame_reversal", isCritical: false },
  { id: 22, text: "He twists my reaction into the “real problem.”", subscale: "blame_reversal", isCritical: false },
  { id: 23, text: "He frames himself as the one being attacked when I ask for accountability.", subscale: "blame_reversal", isCritical: true },
  { id: 24, text: "After conflict, I feel guilty even when I started with a reasonable concern.", subscale: "blame_reversal", isCritical: false },
  { id: 25, text: "He suddenly says he does not understand me when the point is clear.", subscale: "confusion_tactics", isCritical: false },
  { id: 26, text: "He refuses to answer direct questions and then says I am the confusing one.", subscale: "confusion_tactics", isCritical: false },
  { id: 27, text: "He changes the subject when I bring up specific behavior.", subscale: "confusion_tactics", isCritical: false },
  { id: 28, text: "He gives long explanations that leave me more confused than before.", subscale: "confusion_tactics", isCritical: true },
  { id: 29, text: "He focuses on my tone instead of what actually happened.", subscale: "confusion_tactics", isCritical: false },
  { id: 30, text: "He says the conversation is pointless, crazy, or impossible when I try to clarify facts.", subscale: "confusion_tactics", isCritical: false },
  { id: 31, text: "He shuts down, stonewalls, or disappears after creating confusion.", subscale: "confusion_tactics", isCritical: false },
  { id: 32, text: "I often leave conversations without a clear answer to a simple concern.", subscale: "confusion_tactics", isCritical: false },
  { id: 33, text: "He suggests my friends, family, or therapist are putting ideas in my head.", subscale: "isolation_control", isCritical: true },
  { id: 34, text: "He makes me feel disloyal for checking my experience with other people.", subscale: "isolation_control", isCritical: false },
  { id: 35, text: "He prefers that I rely on his version of events instead of outside perspectives.", subscale: "isolation_control", isCritical: false },
  { id: 36, text: "He acts threatened when I seek advice or validation from others.", subscale: "isolation_control", isCritical: false },
  { id: 37, text: "He uses affection, withdrawal, or silence to pressure me into accepting his version.", subscale: "isolation_control", isCritical: true },
  { id: 38, text: "He makes me feel that keeping the peace matters more than telling the truth.", subscale: "isolation_control", isCritical: false },
  { id: 39, text: "I censor what I say to other people because I expect I will end up defending him.", subscale: "isolation_control", isCritical: false },
  { id: 40, text: "I feel more dependent on his interpretation than I used to.", subscale: "isolation_control", isCritical: false },
  { id: 41, text: "I second-guess myself more in this relationship than in past relationships.", subscale: "self_trust_erosion", isCritical: false },
  { id: 42, text: "I ask myself whether I am too sensitive, dramatic, or unreasonable.", subscale: "self_trust_erosion", isCritical: false },
  { id: 43, text: "I feel confused after conversations that should have been simple.", subscale: "self_trust_erosion", isCritical: false },
  { id: 44, text: "I have become less confident in my judgment or memory.", subscale: "self_trust_erosion", isCritical: false },
  { id: 45, text: "I apologize more than I used to.", subscale: "self_trust_erosion", isCritical: false },
  { id: 46, text: "I find it harder to make ordinary decisions.", subscale: "self_trust_erosion", isCritical: false },
  { id: 47, text: "I hide parts of this relationship from other people.", subscale: "self_trust_erosion", isCritical: false },
  { id: 48, text: "I feel smaller, less steady, or less like myself around him.", subscale: "self_trust_erosion", isCritical: false },
  { id: 49, text: "I spend a lot of time mentally reviewing what “really” happened.", subscale: "self_trust_erosion", isCritical: false },
  { id: 50, text: "Part of me worries I cannot trust my own mind in this relationship.", subscale: "self_trust_erosion", isCritical: true }
];
